language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: IH0ZoVPvYD9sDX4CikTqQ07/Cl73K+a3RaxMMSis9EJ4O8P1Mq5oUVBSdUGIc7zIhewdGA6b10jYkTuSf062EcojWtu7CzYEtRo8tR9l36ebdrQeV6e2iq0CeyYjMUjxyFNEhpY4Zhl9k48nj4531bdceNMuc9wruMw9tG2SJQ6N3ZXmnKn+ueCy2RqO8KX6lSmFBi56GvuktkdwGcgKy9+vbaXC9GCXCc0qwUBTx8MkQxIzybXqHOWEDElP1aJLDKc8iy2A+m96Zq9Tgm3OaX36JB7lACZf/OJCUm9V3EpdoLqeBga1A6V8ZTMNjKeg4W50wEuryh5P558M+Ihq6Zyk/wLlVGhw63/fZy09vPp+uWMkVojm8ZTM6GU4f0tKwn6f6J4u68dbEbsPUmWHP/9RxVG8fKVUMTlunMMoS+w1znVeG14DzxHVI0VnGSDageG1B147c7qJ+gil3fftPBe0OcUZpQppFYWSQ/Pk6+uO5DkQgiBpQGz7c46BB0M6D0YVoOifa58m2bFLqYKPUI3d62QTjkx7sYG9YBowFQ4mf9INLFexZamBZcEVHpXcXsDsI9T32hLi8L55h3QrLWJqIEUCn9cy2Xuw9UWSxTmqxjLtMBY2vHVTqYPmDfsIQO5xtf8MWBs27b3eooUJIV0PtKc6hMIq+/U6qUhoYhs=
  app: 'aqueous-fjord-79781'
  on:
    repo: ecarlson1201/gift-list-api
