language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NrPY0j0QX1kVoYYCOJB7vWIWcVW8pjLYyyC/ujHs+Ay7imAemUUp3lhApBihqSfYqKWfip5x3Buu2bhXiNvYQYh6jbcw5yX7X89zfDD86jYVmddt6+sNXr4inQnMOIfakPIFE5TebRG9Etd6edPNAGt3zbrHqzFxkNPjiK6ebb7RQDTLp5zu4kIglo/H3MU1NPOHPrOvoJRU6njeq/zGvjW4VcMlVG62EkI/jUp5czMo1ncqGs8eTorzaJ9Pm2bDyKoWAiQL2DmZtqu6Rwg8Njx4FnNQoqNtahJ8euaHQ9t/Chk0/ix5vttPVyf5OHQRorcxqwYMU5qLQIqucY6SvKfkd541ZwJdWw1oAcwwajhghhMyC34oYXnNschJspuGFOuWwsCziLPfutJgpPo4DcVInFaPDLsThPNaPj/CNEVNlcXWoqNLeCrIjerhTn5Uu00yvSN4H0TvQZmsPxubuLxLtqIIP+3ECdNOt8QG0bETI8yfDB+isEPyFYGRGT+x32HxYDH+GgdzUvNn4WQ87EHL7RTZ8HJnu4GeaXzArnXiS28BGy8iaGBONeMEzkjtvKQCPOpUEOEPEvq5BuFUn1ChNJ5uv9OxReyRZJ0XJQjrH/Bhz/KGPj2x9JbgRgv3gbEOIY/kl1MX82TeJ3nHhDnaTwU/uyjPSjF9Ngbs1ng=
  app: aqueous-fjord-79781
  on:
    repo: ecarlson1201/gift-list-api
